stages:
  - test
  - build
  - pre-release
  - release

include:
  project: efficiency/gitlab-ci-template
  file: templates/.common.gitlab-ci.yml

variables:
  CLOSE_SONAR_SCAN: 'true'

lint:
  image: docker.bizseer.com/golangci/golangci-lint:v1.30
  stage: test
  script:
    - golangci-lint run
  only:
    - master

.only_release:
  # only:
  #   - /^v[0-9]+\.[0-9]+\.[0-9]+$/i
  # except:
  #   - branches
  only:
  - master

build:
  image: docker.bizseer.com/library/golang:1.14
  stage: build
  script:
    - export WALLE_VERSION=${CI_BUILD_REF_NAME:1}
    - echo $WALLE_VERSION
    - make bin/walle
    - ./bin/walle version
  extends:
    - .only_release
  artifacts:
    paths:
      - bin/

binary:
  image: docker.bizseer.com/bizseer/ossutil:1.7.0
  stage: pre-release
  variables:
    OSS_ENDPOINT: http://oss-cn-beijing-internal.aliyuncs.com
    RELEASE_PATH: oss://bizseer-public/release/walle
  before_script:
    - ossutil --version
    - ossutil config -e $OSS_ENDPOINT -i $ACCESS_KEY_ID -k $ACCESS_KEY_SECRET
  script:
    - export WALLE_VERSION=${CI_BUILD_REF_NAME:1}
    - echo $WALLE_VERSION
    - WALLE_RELEASE_PATH=$RELEASE_PATH/$WALLE_VERSION/walle
    - echo $WALLE_RELEASE_PATH
    - ossutil cp bin/walle $WALLE_RELEASE_PATH
    - echo $WALLE_RELEASE_PATH > bin/links.txt
  extends:
    - .only_release

docker_image:
  stage: release
  image:
    name: docker.bizseer.com/kaniko-project/executor:v1.3.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - export VERSION=${CI_BUILD_REF_NAME:1}
    - TAG=$CI_REGISTRY/bizseer/walle:$VERSION
    - echo $TAG
    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR/docker \
        --dockerfile $CI_PROJECT_DIR/docker/Dockerfile \
        --destination $TAG \
        --build-arg VERSION=$VERSION
  only:
    - v0.1.4

release_note:
  image: alpine:3.12.3
  stage: release
  extends:
    - .only_release
  before_script:
    - cp bin/walle /usr/local/bin/walle
    - chmod a+x /usr/local/bin/walle
  script:
    - walle version
    - export WALLE_GITLAB_HOST=$CI_SERVER_URL
    - walle release -p $CI_PROJECT_PATH --ref $CI_COMMIT_SHA -t $CI_BUILD_REF_NAME
    - walle changelog -p $CI_PROJECT_PATH --ref $CI_COMMIT_SHA -t $CI_BUILD_REF_NAME --assignee $GITLAB_USER_ID
